### ISSUE TITLE
EC2_OD not working for RedHat

### ISSUE THREAD

**Issue by Tawha** [getstrake/aws-pricing-sheets-addon#15]
=EC2_OD("c5.24xlarge", "af-south-1", "rhel") is giving me following error 

"Found too many instances that matched c5.24xlarge (line 52)."

Same error for 
=EC2_RHEL_OD("c5.24xlarge", "af-south-1")

**Comment by reganbrianpatrick** [comment]
@Tawha this has been fixed in the new version of the add-on: [AWS Pricing by Strake](https://workspace.google.com/marketplace/app/aws_pricing_by_strake/378787760903). The formulas have been updated, so here is the formula you can use to get the same price:

=AWS_EC2("ondemand","c5.24xlarge", "af-south-1", "rhel")

Please let us know if there is anything else we can help with!
